CREATE PUBLIC SYNONYM XXOEM_PAY_MAESTRO_RECIBOS2 FOR XXOEM.XXOEM_PAY_MAESTRO_RECIBOS2;
/
CREATE PUBLIC SYNONYM XXOEM_PAY_RECIBO_PERCEPCIONES2 FOR XXOEM.XXOEM_PAY_RECIBO_PERCEPCIONES2;
/
CREATE PUBLIC SYNONYM XXOEM_PAY_RECIBO_DEDUCCIONES2 FOR XXOEM.XXOEM_PAY_RECIBO_DEDUCCIONES2;
/