CREATE PUBLIC SYNONYM XXOEM_HR_CFDI_DEDUCCIONES FOR XXOEM.XXOEM_HR_CFDI_DEDUCCIONES;
/
CREATE PUBLIC SYNONYM XXOEM_HR_CFDI_EMPLEADOS FOR XOEM.XXOEM_HR_CFDI_EMPLEADOS;
/
CREATE PUBLIC SYNONYM XXOEM_HR_CFDI_HORASEXTRAS FOR XXOEM.XXOEM_HR_CFDI_HORASEXTRAS;
/
CREATE PUBLIC SYNONYM XOEM_HR_CFDI_INCAPACIDADES FOR XXOEM.XOEM_HR_CFDI_INCAPACIDADES;
/
CREATE PUBLIC SYNONYM XXOEM_HR_CFDI_PERCEPCIONES FOR XXOEM.XXOEM_HR_CFDI_PERCEPCIONES;
/