CREATE TABLE xxoem.XXOEM_HR_CFDI_PERCEPCIONES (
RECIBO_ID NUMBER,
NUM_LINEA NUMBER,
CLAVE VARCHAR2(15),--CONCEPTO,
TIPO_PER VARCHAR2(1000),
DESCRIPCION_PER VARCHAR(1000),
IMPORTE NUMBER,
IMPORTE_PERCEPCIONES NUMBER,
ELEMENT_TYPE_ID NUMBER,
DIAS_PER NUMBER,
GRAVADO_PER NUMBER,
EXENTO_PER NUMBER,
ID_DATOS VARCHAR(1)
);
/
GRANT ALL ON XXOEM_HR_CFDI_PERCEPCIONES TO APPS;
/

