CREATE TABLE XXOEM.XXOEM_HR_CFDI_EMPLEADOS
(
  RECIBO_ID          NUMBER,
  ID_NOMINA          NUMBER,
  NUMERO_EMPLEADO    VARCHAR2(30 BYTE),
  FECHA_PAGO         DATE,
  FECHA_INICIAL      DATE,
  FECHA_FINAL        DATE,
  DIAS_PAGADOS       NUMBER,
  SALARIO_BASE_COT   NUMBER,
  SDI                NUMBER,
  DECRIPCION         VARCHAR2(100 BYTE),
  TIME_PERIOD_ID     NUMBER,
  PERSON_ID          NUMBER,
  PAYROLL_ACTION_ID  NUMBER,
  ID_DATOS           VARCHAR2(1 BYTE),
  UUID               VARCHAR2(50 BYTE),
  SERIE              VARCHAR2(50 BYTE),
  FOLIO              NUMBER,
  CADENATFD          VARCHAR2(4000 BYTE),
  NOCERTSAT          VARCHAR2(50 BYTE),
  CERTEMISOR         VARCHAR2(50 BYTE),
  FECHASAT           VARCHAR2(50 BYTE),
  SELLOSAT           VARCHAR2(4000 BYTE),
  SELLOCFDI          VARCHAR2(4000 BYTE),
  RUTAQR             VARCHAR2(4000 BYTE),
  ESTATUS            NUMBER  DEFAULT 0,
  NUM_SEGURO_SOCIAL  VARCHAR2(1000),
  ATTRIBUTE1         VARCHAR2(1000 BYTE),
  ATTRIBUTE2         VARCHAR2(1000 BYTE),
  ATTRIBUTE3         VARCHAR2(1000 BYTE),
  ATTRIBUTE4         VARCHAR2(1000 BYTE),
  ATTRIBUTE5         VARCHAR2(1000 BYTE)
)
TABLESPACE XXOEM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
/
grant all on XXOEM.XXOEM_HR_CFDI_EMPLEADOS to apps;
/