CREATE TABLE XXOEM.XXOEM_HR_CFDI_INCAPACIDADES (   
RECIBO_ID NUMBER,
NUM_LINEA NUMBER,
TIPO_INC varchar(100),
DESCUENTO_INC NUMBER,
ELEMENT_TYPE_ID NUMBER,
DIAS_INC NUMBER,
ID_DATOS VARCHAR2(1)               
);
/
GRANT ALL ON XXOEM_HR_CFDI_INCAPACIDADES TO APPS;
/  